model_list:

  # --- AIHubmix (聚合平台) ---
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: "os.environ/AIHUBMIX_KEY"
      api_base: https://aihubmix.com/v1


router_settings:
  routing_strategy: simple-shuffle
  num_retries: 2
  timeout: 60
